from PySide2 import QtCore
from PySide2.QtGui import QFont
from PySide2.QtWidgets import QGroupBox, QVBoxLayout, QLabel, QFrame, QSizePolicy, QHBoxLayout, QComboBox, QLineEdit, \
    QPushButton, QScrollArea


# TODO REGISTERS ROW, + BUTTON ETC...
class CurrentStateWindow:

    def __init__(self, state_manager):
        self.state_manager = state_manager
        self.isFirst = True
        self.more_data = []
        self.last_ten_dicts = []
        self.rows = None
        self.table_view = None

    def init_current_state_window(self, font):
        lower_box = QGroupBox()

        lower_layout = QVBoxLayout()
        lower_layout.setAlignment(QtCore.Qt.AlignTop)

        underline_font = QFont("Arial", 12)
        underline_font.setUnderline(True)

        current_state_label = QLabel("Current States:")
        current_state_label.setFont(underline_font)
        lower_layout.addWidget(current_state_label)

        current_state_line = QFrame()
        current_state_line.setFrameShape(QFrame.HLine)
        current_state_line.setFrameShadow(QFrame.Sunken)
        current_state_line.setSizePolicy(QSizePolicy.Minimum, QSizePolicy.Preferred)
        lower_layout.addWidget(current_state_line)

        coils_parent_box = QGroupBox()
        coils_parent_layout = QVBoxLayout()
        coils_label = QLabel("Coils")
        coils_label.setAlignment(QtCore.Qt.AlignCenter)
        coils_label.setFont(underline_font)
        coils_parent_layout.addWidget(coils_label)
        coils_parent_box.setLayout(coils_parent_layout)
        coils_second_row_layout = QHBoxLayout()
        coil_select_box = QGroupBox()
        coil_select_box.setMaximumWidth(350)
        coil_select_layout = QHBoxLayout()
        coil_select_layout.setAlignment(QtCore.Qt.AlignLeft)
        coil_select_label = QLabel("Start Address(hex):")
        coil_select_layout.addWidget(coil_select_label)
        coil_input = QLineEdit()
        coil_input.setAlignment(QtCore.Qt.AlignLeft)
        coil_input.setPlaceholderText("Insert...")
        coil_select_layout.addWidget(coil_input)
        coil_select_box.setLayout(coil_select_layout)
        coils_second_row_layout.addWidget(coil_select_box)
        coil_scroll = QScrollArea()
        coil_scroll.setWidgetResizable(True)
        coil_scroll.setMaximumHeight(60)
        coil_result_label = QLabel("TODO PUT COIL STATUS HERE=======================================================")
        coil_scroll.setWidget(coil_result_label)
        coils_second_row_layout.addWidget(coil_scroll)
        coil_more_button = QPushButton("+")
        coil_more_button.setMaximumWidth(50)
        coil_more_button.setStyleSheet("background-color: green")
        coil_more_button.setFont(font)
        coils_second_row_layout.addWidget(coil_more_button)
        coils_parent_layout.addLayout(coils_second_row_layout)
        lower_layout.addWidget(coils_parent_box)

        discrete_inputs_parent_box = QGroupBox()
        discrete_inputs_parent_layout = QVBoxLayout()
        discrete_inputs_label = QLabel("Discrete Inputs.")
        discrete_inputs_label.setAlignment(QtCore.Qt.AlignCenter)
        discrete_inputs_label.setFont(underline_font)
        discrete_inputs_parent_layout.addWidget(discrete_inputs_label)
        discrete_inputs_parent_box.setLayout(discrete_inputs_parent_layout)
        discrete_inputs_second_row_layout = QHBoxLayout()
        discrete_inputs_select_box = QGroupBox()
        discrete_inputs_select_box.setMaximumWidth(350)
        discrete_inputs_select_layout = QHBoxLayout()
        discrete_inputs_select_layout.setAlignment(QtCore.Qt.AlignLeft)
        discrete_inputs_select_label = QLabel("Start Address(hex):")
        discrete_inputs_select_layout.addWidget(discrete_inputs_select_label)
        discrete_inputs_input = QLineEdit()
        discrete_inputs_input.setAlignment(QtCore.Qt.AlignLeft)
        discrete_inputs_input.setPlaceholderText("Insert...")
        discrete_inputs_select_layout.addWidget(discrete_inputs_input)
        discrete_inputs_select_box.setLayout(discrete_inputs_select_layout)
        discrete_inputs_second_row_layout.addWidget(discrete_inputs_select_box)
        discrete_inputs_second_row_layout_scroll = QScrollArea()
        discrete_inputs_second_row_layout_scroll.setWidgetResizable(True)
        discrete_inputs_second_row_layout_scroll.setMaximumHeight(60)
        discrete_inputs_second_row_layout_result_label = QLabel(
            "TODO PUT DISC, INPUT STATUS HERE=======================================================")
        discrete_inputs_second_row_layout_scroll.setWidget(discrete_inputs_second_row_layout_result_label)
        discrete_inputs_second_row_layout.addWidget(discrete_inputs_second_row_layout_scroll)
        discrete_inputs_second_row_layout_more_button = QPushButton("+")
        discrete_inputs_second_row_layout_more_button.setMaximumWidth(50)
        discrete_inputs_second_row_layout_more_button.setStyleSheet("background-color: green")
        discrete_inputs_second_row_layout_more_button.setFont(font)
        discrete_inputs_second_row_layout.addWidget(discrete_inputs_second_row_layout_more_button)
        discrete_inputs_parent_layout.addLayout(discrete_inputs_second_row_layout)
        lower_layout.addWidget(discrete_inputs_parent_box)


        discrete_inputs_parent_box = QGroupBox()
        discrete_inputs_parent_layout = QVBoxLayout()
        discrete_inputs_label = QLabel("Discrete Inputs.")
        discrete_inputs_label.setAlignment(QtCore.Qt.AlignCenter)
        discrete_inputs_label.setFont(underline_font)
        discrete_inputs_parent_layout.addWidget(discrete_inputs_label)
        discrete_inputs_parent_box.setLayout(discrete_inputs_parent_layout)
        discrete_inputs_second_row_layout = QHBoxLayout()
        discrete_inputs_select_box = QGroupBox()
        discrete_inputs_select_box.setMaximumWidth(350)
        discrete_inputs_select_layout = QHBoxLayout()
        discrete_inputs_select_layout.setAlignment(QtCore.Qt.AlignLeft)
        discrete_inputs_select_label = QLabel("Start Address(hex):")
        discrete_inputs_select_layout.addWidget(discrete_inputs_select_label)
        discrete_inputs_input = QLineEdit()
        discrete_inputs_input.setAlignment(QtCore.Qt.AlignLeft)
        discrete_inputs_input.setPlaceholderText("Insert...")
        discrete_inputs_select_layout.addWidget(discrete_inputs_input)
        discrete_inputs_select_box.setLayout(discrete_inputs_select_layout)
        discrete_inputs_second_row_layout.addWidget(discrete_inputs_select_box)
        discrete_inputs_second_row_layout_scroll = QScrollArea()
        discrete_inputs_second_row_layout_scroll.setWidgetResizable(True)
        discrete_inputs_second_row_layout_scroll.setMaximumHeight(60)
        discrete_inputs_second_row_layout_result_label = QLabel(
            "TODO PUT DISC, INPUT STATUS HERE=======================================================")
        discrete_inputs_second_row_layout_scroll.setWidget(discrete_inputs_second_row_layout_result_label)
        discrete_inputs_second_row_layout.addWidget(discrete_inputs_second_row_layout_scroll)
        discrete_inputs_second_row_layout_more_button = QPushButton("+")
        discrete_inputs_second_row_layout_more_button.setMaximumWidth(50)
        discrete_inputs_second_row_layout_more_button.setStyleSheet("background-color: green")
        discrete_inputs_second_row_layout_more_button.setFont(font)
        discrete_inputs_second_row_layout.addWidget(discrete_inputs_second_row_layout_more_button)
        discrete_inputs_parent_layout.addLayout(discrete_inputs_second_row_layout)
        lower_layout.addWidget(discrete_inputs_parent_box)

        discrete_inputs_parent_box = QGroupBox()
        discrete_inputs_parent_layout = QVBoxLayout()
        discrete_inputs_label = QLabel("Discrete Inputs.")
        discrete_inputs_label.setAlignment(QtCore.Qt.AlignCenter)
        discrete_inputs_label.setFont(underline_font)
        discrete_inputs_parent_layout.addWidget(discrete_inputs_label)
        discrete_inputs_parent_box.setLayout(discrete_inputs_parent_layout)
        discrete_inputs_second_row_layout = QHBoxLayout()
        discrete_inputs_select_box = QGroupBox()
        discrete_inputs_select_box.setMaximumWidth(350)
        discrete_inputs_select_layout = QHBoxLayout()
        discrete_inputs_select_layout.setAlignment(QtCore.Qt.AlignLeft)
        discrete_inputs_select_label = QLabel("Start Address(hex):")
        discrete_inputs_select_layout.addWidget(discrete_inputs_select_label)
        discrete_inputs_input = QLineEdit()
        discrete_inputs_input.setAlignment(QtCore.Qt.AlignLeft)
        discrete_inputs_input.setPlaceholderText("Insert...")
        discrete_inputs_select_layout.addWidget(discrete_inputs_input)
        discrete_inputs_select_box.setLayout(discrete_inputs_select_layout)
        discrete_inputs_second_row_layout.addWidget(discrete_inputs_select_box)
        discrete_inputs_second_row_layout_scroll = QScrollArea()
        discrete_inputs_second_row_layout_scroll.setWidgetResizable(True)
        discrete_inputs_second_row_layout_scroll.setMaximumHeight(60)
        discrete_inputs_second_row_layout_result_label = QLabel(
            "TODO PUT DISC, INPUT STATUS HERE=======================================================")
        discrete_inputs_second_row_layout_scroll.setWidget(discrete_inputs_second_row_layout_result_label)
        discrete_inputs_second_row_layout.addWidget(discrete_inputs_second_row_layout_scroll)
        discrete_inputs_second_row_layout_more_button = QPushButton("+")
        discrete_inputs_second_row_layout_more_button.setMaximumWidth(50)
        discrete_inputs_second_row_layout_more_button.setStyleSheet("background-color: green")
        discrete_inputs_second_row_layout_more_button.setFont(font)
        discrete_inputs_second_row_layout.addWidget(discrete_inputs_second_row_layout_more_button)
        discrete_inputs_parent_layout.addLayout(discrete_inputs_second_row_layout)
        lower_layout.addWidget(discrete_inputs_parent_box)

        lower_box.setLayout(lower_layout)
        return lower_box


def update_current_state(coil_or_reg, number_of):
    print("update_current_state")
    print(coil_or_reg, number_of)
